---
title: "Curso cero de Física"
title-block-banner: true
lang: es
execute:
  echo: false
format: 
  html:
    toc: false
    page-layout: full
    format-links: true
    lightbox: true
    
---

Curso cero de Física para la ETSIIT y la Facultad de Ciencias de la Universidad de Granada. Puedes encontrar otros cursos cero de nuestro centro en este [enlace](https://cursos-0-fc-ugr.github.io/).

Este repositorio se puede visitar en [GitHub pages](https://github.com/cursos-0-fc-ugr/Fisica).

Para esta edición se han actualizado los contenidos y adaptado a la LOMLOE. La versión anterior está disponible en este [enlace](https://cursos-0-fc-ugr.github.io/Fisica/Curso_old/).

Si encuentra algún error, por favor, comuníquenoslo usando el [gestor de incidencias](https://github.com/cursos-0-fc-ugr/Fisica/issues) de este repositorio.

# Temas

- [Tema 0. Vectores](Tema0_Vectores/)
- [Tema 1. Cinemática](Tema1_Cinematica/)
- [Tema 2. Dinámica](Tema2_Dinamica/)
- [Tema 3. Energía](Tema3_Energia/)
- [Tema 4. Campo gravitatorio](Tema4_Campo_Gravitatorio/)
- [Tema 5. Campo electrostático](Tema5_Campo_Electrostatico/)
- [Tema 6. Electromagnetismo](Tema6_Electromagnetismo/)
- [Tema 7. Oscilaciones y ondas](Tema7_Oscilaciones_Ondas/)
- [Tema 8. Óptica](Tema8_Optica/)